#!/usr/bin/env bash

# Check if an argument (IP address) is provided
# '$1' = the first argument (adress ip)
# '-z' = vide ?
# message
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# if not ping 5 times
# Ping the given IP address 5 times
ping -c 5 "$1"